version: '3.8'

services:
  dbs:
    image: postgres:13.7-alpine
    volumes:
      - /var/lib/postgresql/data
    environment:
      - POSTGRES_DB=whynotes
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
    ports:
      - "5432:5432"

  web:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - dbs
    environment:
      spring.datasource.url: "jdbc:postgresql://dbs:5432/whynotes"