version: '3.8'

services:
  db:
    image: postgres:13.7-alpine
    volumes:
      - /var/lib/postgresql/data
    environment:
      - POSTGRES_DB=whynotes
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root

  web:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      spring.datasource.url: "jdbc:postgresql://localhost:5432/whynotes"